INSERT INTO teams (ID, Nome, Cidade, SuperBowlsGanhos, JogosForaDoPais) VALUES
(1,  'New England Patriots',    'Foxborough, MA',      6, 2),
(2,  'Pittsburgh Steelers',     'Pittsburgh, PA',      6, 1),
(3,  'San Francisco 49ers',     'Santa Clara, CA',     5, 1),
(4,  'Dallas Cowboys',          'Arlington, TX',       5, 3),
(5,  'Green Bay Packers',       'Green Bay, WI',       4, 0),
(6,  'New York Giants',         'East Rutherford, NJ', 4, 1),
(7,  'Kansas City Chiefs',      'Kansas City, MO',     4, 3),
(8,  'Denver Broncos',          'Denver, CO',          3, 0),
(9,  'Las Vegas Raiders',       'Las Vegas, NV',       3, 2),
(10, 'Washington Commanders',   'Landover, MD',        3, 1),
(11, 'Miami Dolphins',          'Miami, FL',           2, 1),
(12, 'Baltimore Ravens',        'Baltimore, MD',       2, 1),
(13, 'Tampa Bay Buccaneers',    'Tampa, FL',           2, 3),
(14, 'Los Angeles Rams',        'Inglewood, CA',       2, 4),
(15, 'Indianapolis Colts',      'Indianapolis, IN',    2, 1),
(16, 'Chicago Bears',           'Chicago, IL',         1, 2),
(17, 'New York Jets',           'East Rutherford, NJ', 1, 1),
(18, 'Seattle Seahawks',        'Seattle, WA',         1, 2),
(19, 'New Orleans Saints',      'New Orleans, LA',     1, 1),
(20, 'Philadelphia Eagles',     'Philadelphia, PA',    1, 2),
(21, 'Arizona Cardinals',       'Glendale, AZ',        0, 2),
(22, 'Buffalo Bills',           'Orchard Park, NY',    0, 2),
(23, 'Carolina Panthers',       'Charlotte, NC',       0, 1),
(24, 'Cincinnati Bengals',      'Cincinnati, OH',      0, 1),
(25, 'Cleveland Browns',        'Cleveland, OH',       0, 1),
(26, 'Detroit Lions',           'Detroit, MI',         0, 2),
(27, 'Houston Texans',          'Houston, TX',         0, 1),
(28, 'Jacksonville Jaguars',    'Jacksonville, FL',    0, 5),
(29, 'Minnesota Vikings',       'Minneapolis, MN',     0, 1),
(30, 'Tennessee Titans',        'Nashville, TN',       0, 0),
(31, 'Atlanta Falcons',         'Atlanta, GA',         0, 1),
(32, 'Los Angeles Chargers',    'Inglewood, CA',       0, 1);